#!/usr/bin/env sh

INSTALL="$HOME/.local"
share="$INSTALL/share/nano"

# kagami flavored markdown takes priority
rm -f "$share/markdown.nanorc"

# inject custom syntax rules for C-like languages
for f in c javascript; do
	syn="$share/$f.nanorc"
	{	rm "$syn"
		sed "/^comment/r $share/stdc.syntax" > "$syn"
	} < "$syn"
done
