#!/usr/bin/env sh

# install build prereqs
is-installed \
	libncurses-dev autoconf automake autopoint gettext texinfo \
	| xargs -r sudo apt-get -y install

# required for automake
[ ! -d 'gnulib' ] && ./autogen.sh
