#!/usr/bin/env sh

# install automake and other dependencies
sudo apt-get -y install \
	libncurses-dev autoconf automake autopoint gettext texinfo

# required for automake
[ ! -d 'gnulib' ] && ./autogen.sh
