# ~/.config/chromium/local_state.conf: persistent flags for chromium 146

background_mode.enabled = false

# overwrites all existing flags
# disable smooth-scrolling
browser.enabled_labs_experiments = [ "smooth-scrolling@2" ]

# enable vertical tabstrip in settings
browser.enabled_labs_experiments += [ "vertical-tabs@1" ]
