#!/usr/bin/env sh

# Usage: visual [command]
# X window shim for terminal applications
# force-run in a new terminal window if X is running

unset shim
if [ ! -z "$DISPLAY" ]; then
	case "$(tty)" in
		# previously triggered on 'not a tty'
		*) shim='urxvtc -e';;
	esac
fi

$shim "$@"
