#!/usr/bin/env sh

# prompt user to Yes/No confirm destructive actions
# '-d' for dialog boxes without choices
# usage: x-user-confirm [-d] "[prompt text]"

[ ! -z "$1" ] || exit 1

if [ "$1" = '-d' ]; then
	shift
	xmessage -default 'Okay' -buttons 'Okay' "$@"
else
	case "$(xmessage -buttons 'Yes,No' -print "$@")" in
		No) return 1;;
	esac
fi

return 0
