#!/usr/bin/env sh

# requires dotnet-sdk-8.0 to build
eval "$(cat /etc/os-release)"
SOURCE='https://packages.microsoft.com/config/debian'
DEB='packages-microsoft-prod.deb'

wget "$SOURCE/$VERSION_ID/$DEB"
sudo dpkg -i "$DEB"
sudo apt-get update

# install build prereqs
is-installed libx11-dev libxrandr-dev libevdev-dev \
	libgtk-3-dev dotnet-sdk-8.0 | xargs -r sudo apt-get -y install

# build and install debian package
# should install runtime prereqs from microsoft repos
./eng/linux/package.sh --package Debian
sudo dpkg -i dist/*.deb

# dotnet-sdk is very bloated and isn't used again, delete
sudo apt-get -y autoremove --purge dotnet-sdk-8.0
rm -rf "$XDG_DATA_HOME/NuGet" ~/.dotnet ~/.nuget # WTF!!!

# bypass ~/.once.d/10-git-upstream.sh
cat <<- EOF > Makefile
	install:
		:
EOF

