#!/usr/bin/env sh

# 2023/04: upstream dev started modernizing build process and stripped out
# automake in favor of plain make, reverting to last known good commit for now
git checkout legacy

# install build prereqs
is-installed libxt-dev autoconf automake \
	| xargs -r sudo apt-get -y install

# 2025/08: src/serial.c is pretty unimportant and has implicit function
# declarations that have turned into compile-time errors in debian 13 (trixie)
mv -v src/serial.c src/tmp.c
cat <<- EOF > src/serial.c
	void grantpt() { ; }
	void unlockpt() { ; }
	int ptsname_r(int, char *, int) { ; }
EOF
cat src/tmp.c >> src/serial.c
rm src/tmp.c

./autogen.sh
