#!/usr/bin/env sh

is-installed libx11-dev libxft-dev libxinerama-dev \
	| xargs -r sudo apt-get -y install

# apply quality of life patches
if [ -d patches ]; then
	for g in patches/*.diff; do
		echo "[patch] $g..."
		patch < $g || exit 1
	done
fi

