#!/bin/sh

# launches SSH daemon for sharing resources from android
# generates usage instructions to make connecting easier

port=8022
user=$(whoami)

# get local device IP
# android 13+ blocks access to /proc/net
#ip=$(ip -o addr | grep -F 'wlan' | grep -Eo '([0-9]{1,3}\.?){4}' | head -n 1)
ip="$(ifconfig | grep -A1 'wlan' | tail -n 1 | egrep -o '([0-9]{1,3}\.?){4}' | head -n 1)" 2> /dev/null

# get path to external sdcard if it exists
# paths take the form /storage/XXXX-XXXX
int_path="$(readlink ~/storage/shared)"
ext_path="$(readlink ~/storage/external* | head -n 1)"
if [ ! -z "$ext_path" ]; then
	while [ "$(echo "$ext_path" | tr -cd '/' | wc -c)" -gt 2 ]; do
		ext_path="${ext_path%/*}"
	done
fi

# splash screen
cat <<- EOF
	$(printf '\33[1m%s\33[0m' "${0##*/}")
	usage: ssh -p $port $user@${ip:-localhost (no WLAN connection)}

	internal: $int_path
	external: $ext_path

	$(printf '\33[1m%s\33[0m' '^C to exit.')

EOF

# quick start QR code
if [ ! -z "$ip" ]; then
	qrencode -m 2 -t ANSIUTF8 "sshfs -p $port -o reconnect $user@$ip:$int_path /media/sftp_tunnel"
	printf '%s\n\n' 'usage (on PC): qr -d | sh'
fi

# release wakelock and return 0 on SIGINT
quit() {
	termux-wake-unlock &
	:
}

# acquire wakelock
# run in foreground, android hates forking daemons
stty -echo
trap quit 2
termux-wake-lock &
sshd -p $port -D -e 2>&1 | ts '[%a %b %_d %_H:%M:%S]'
