#!/usr/bin/env sh

# install build prereqs
is-installed bison libncurses-dev | xargs -r sudo apt-get -y install

# n-t-roff/sc uses minimal drop-in replacement for autoconf
# patches configure to ignore options
# patches Makefile.in.vpath to use $HOME/.local
patch -p1 < fake-autoconf.diff

# let ~/.once.d/10-git-upstream.sh harmlessly run these again
# generated Makefile chokes if you run 'make install' in one go
./configure
make
