#!/usr/bin/env sh

# install build prereqs
is-installed libpango1.0-dev libfm-dev libgtk2.0-dev libfm-gtk-dev \
	| xargs -r sudo apt-get -y install

# last known good ver
git checkout '1.4.0'

# HACK: offset icons in --desktop mode for use with tiling wms
patch -p1 < desktop-icon-offset.patch

# autogen.sh generates a ./configure script that breaks the build process if
# this one line isn't deleted
./autogen.sh
sed -i '/IT_PROG_INTLTOOL/d' configure
./configure --prefix="$HOME/.local"

# then the generated Makefile regenerates and calls autogen.sh and configure AGAIN
# this is an attempt to prevent this behavior
touch autogen.sh configure

# first make invocation always errors out
make
# second make invocation always works, what the fuck is this build process
make
make install

# disarm makefile, ~/.once.d/10-git-upstream.sh will return
# non-zero if allowed to continue normally
rm -f autogen.sh configure
cat <<- EOF > Makefile
	install:
		:
EOF
