#!/usr/bin/env sh

# install build prereqs
is-installed libpango1.0-dev libfm-dev libgtk2.0-dev libfm-gtk-dev intltool \
	| xargs -r sudo apt-get -y install

# last known good ver
git checkout '1.4.0'

# HACK: offset icons in --desktop mode for use with tiling wms
patch -p1 < desktop-icon-offset.patch

# pcmanfm likes to drop default settings in /etc which aren't needed
# not running make twice errors out the build process for some reason
./autogen.sh
./configure --prefix="$HOME/.local" --sysconfdir=/dev/null
make
make install

# disarm makefile, ~/.once.d/10-git-upstream.sh will return
# non-zero if allowed to continue normally
rm -f autogen.sh configure
cat <<- EOF > Makefile
	install:
		:
EOF
