name: CI
on:
  push:
    paths:
    - .github/workflows/*
    - .profile
    - .bashrc
    - .local/bin/*
    - .once.d/*
    - Scripts/*

jobs:
  Install:
     runs-on: ubuntu-latest
     container: debian:bullseye
     steps:
       - name: Install prerequisites
         run: apt-get update && apt-get install -y git wget sudo
       - name: Checkout dotfiles
         run: git clone --bare https://github.com/microsounds/atelier ~/.config/meta
       - name: Bootstrap system
         run: git --git-dir=$HOME/.config/meta --work-tree=$HOME reset --hard
       - name: Run post-install scripts
         shell: bash -le {0}
         env:
           TERM: rxvt
         run: yes n | post-install
       - name: Run shell environment tests
         shell: bash -le {0}
         env:
           TERM: rxvt
         run: |
           fgrep 'stdc.syntax' < ~/.local/share/nano/c.nanorc
           colors
           cpp -P <<- EOF
               #include <colors/nightdrive.h>
           EOF
           twopass ffmpeg -loglevel quiet -s 1920x1080 -t 0.2 -f rawvideo \
             -i /dev/urandom -c:v libvpx -b:v 100M -an noise.webm
           mpv --vo=null noise.webm
           screenfetch
       - name: Run nano_overlay and openssl tests
         shell: bash -le {0}
         env:
           TERM: rxvt
           EXTERN_EDITOR: cat
           SECRET: ">‿<"
         run: |
           mkdir ~/.ssh
           ssh-keygen -f ~/.ssh/id_rsa -t rsa -b 4096 -N '' -m pem
           echo "$SECRET" > ok
           yes y | nano-overlay -j ok
           { xz -d | tar -xO enc | file -; } < ok | fgrep 'openssl'
           nano-overlay -j ok | fgrep "$SECRET" && \
             printf '\e[1;30;102m%s\e[0m\n' "ALL TESTS OK $SECRET"
