name: CI
on:
  push:
    paths:
    - .profile
    - .bashrc
    - .once.d/*

jobs:
  Install:
     runs-on: ubuntu-latest
     container: debian:stable
     steps:
       - name: Install prerequisites
         run: apt-get update && apt-get install -y git wget sudo
       - name: Checkout dotfiles
         run: git clone --bare https://github.com/microsounds/atelier ~/.config/meta
       - name: Bootstrap system
         run: git --git-dir=$HOME/.config/meta --work-tree=$HOME reset --hard
       - name: Run post-install scripts
         shell: bash -le {0}
         env:
           TERM: rxvt
         run: yes n | post-install
       - name: Run environment smoke tests
         shell: bash -le {0}
         env:
           TERM: rxvt
         run: |
           colors
           nano -V && fgrep -q 'stdc.syntax' < ~/.local/share/nano/c.nanorc 
           echo '#include <colors/nightdrive.h>' | cpp
           twopass ffmpeg -loglevel quiet -s 1920x1080 -t 0.1 -f rawvideo \
             -i /dev/urandom -c:v libvpx -b:v 100M -an noise.webm
